# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calorie.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'calorie.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcalorie.proto\"\x15\n\x05Plate\x12\x0c\n\x04name\x18\x01 \x01(\x03\"`\n\x0f\x43\x61lorieResponse\x12\x0c\n\x04\x66ood\x18\x01 \x01(\x03\x12\x10\n\x08\x63\x61lories\x18\x02 \x01(\x02\x12\r\n\x05\x63\x61rbs\x18\x03 \x01(\x02\x12\x10\n\x08proteins\x18\x05 \x01(\x02\x12\x0c\n\x04\x66\x61ts\x18\x06 \x01(\x02\x32?\n\x0e\x43\x61lorieService\x12-\n\x11\x43\x61lculateCalories\x12\x06.Plate\x1a\x10.CalorieResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calorie_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLATE']._serialized_start=17
  _globals['_PLATE']._serialized_end=38
  _globals['_CALORIERESPONSE']._serialized_start=40
  _globals['_CALORIERESPONSE']._serialized_end=136
  _globals['_CALORIESERVICE']._serialized_start=138
  _globals['_CALORIESERVICE']._serialized_end=201
# @@protoc_insertion_point(module_scope)
