name: Commit Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install dependencies (including commitlint)
      - name: Install dependencies
        run: npm install

      # Install commitlint and lint the commits
      - name: Lint commits
        run: npx commitlint --from=HEAD~1 --to=HEAD